databaseChangelog:
  - changeset:
      id: 1
      author: Christina
      changes:
        - createTable:
            tableName: product
            columns:
              - column:
                  name: id
                  type: INT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: price
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: amount
                  type: INT
                  constraints:
                    nullable: false
              - column:
                  name: warehouse_id
                  type: INT
                  constraints:
                    nullable: false